config/routes.rb
Rails.application.routes.draw do
  resources :wiki_posts
  get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  get "welcome/about"
  get "/about", to:("/welcome/about")
  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/wiki_post.rb
class WikiPost < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wiki_posts_controller.rb
class WikiPostsController < ApplicationController
  before_action :set_wiki_post, only: %i[ show edit update destroy ]

  # GET /wiki_posts or /wiki_posts.json
  def index
    @wiki_posts = WikiPost.all
  end

  # GET /wiki_posts/1 or /wiki_posts/1.json
  def show
    render "example"
  end

  # GET /wiki_posts/new
  def new
    @wiki_post = WikiPost.new
  end

  # GET /wiki_posts/1/edit
  def edit
  end

  # POST /wiki_posts or /wiki_posts.json
  def create
    @wiki_post = WikiPost.new(wiki_post_params)

    respond_to do |format|
      if @wiki_post.save
        format.html { redirect_to wiki_post_url(@wiki_post), notice: "Wiki post was successfully created." }
        format.json { render :show, status: :created, location: @wiki_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wiki_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wiki_posts/1 or /wiki_posts/1.json
  def update
    respond_to do |format|
      if @wiki_post.update(wiki_post_params)
        format.html { redirect_to wiki_post_url(@wiki_post), notice: "Wiki post was successfully updated." }
        format.json { render :show, status: :ok, location: @wiki_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wiki_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wiki_posts/1 or /wiki_posts/1.json
  def destroy
    @wiki_post.destroy!

    respond_to do |format|
      format.html { redirect_to wiki_posts_url, notice: "Wiki post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki_post
      @wiki_post = WikiPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wiki_post_params
      params.fetch(:wiki_post, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wiki_posts_helper.rb
module WikiPostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Hello, World!</p>

app/views/wiki_posts/_form.html.erb
<%= form_with(model: wiki_post) do |form| %>
  <% if wiki_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wiki_post.errors.count, "error") %> prohibited this wiki_post from being saved:</h2>

      <ul>
        <% wiki_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wiki_posts/_wiki_post.html.erb
<div id="<%= dom_id wiki_post %>">
</div>

app/views/wiki_posts/edit.html.erb
<h1>Editing wiki post</h1>

<%= render "form", wiki_post: @wiki_post %>

<br>

<div>
  <%= link_to "Show this wiki post", @wiki_post %> |
  <%= link_to "Back to wiki posts", wiki_posts_path %>
</div>

app/views/wiki_posts/example.html.erb
<h1>Wiki Page Title</h1>

app/views/wiki_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Wiki posts</h1>

<div id="wiki_posts">
  <% @wiki_posts.each do |wiki_post| %>
    <%= render wiki_post %>
    <p>
      <%= link_to "Show this wiki post", wiki_post %>
    </p>
  <% end %>
</div>

<%= link_to "New wiki post", new_wiki_post_path %>

app/views/wiki_posts/new.html.erb
<h1>New wiki post</h1>

<%= render "form", wiki_post: @wiki_post %>

<br>

<div>
  <%= link_to "Back to wiki posts", wiki_posts_path %>
</div>

app/views/wiki_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @wiki_post %>

<div>
  <%= link_to "Edit this wiki post", edit_wiki_post_path(@wiki_post) %> |
  <%= link_to "Back to wiki posts", wiki_posts_path %>

  <%= button_to "Destroy this wiki post", @wiki_post, method: :delete %>
</div>